l=list(map(int,input("enter the elements\n").split()))
t=tuple(l)
print(t) 
x=int(input("enter the insert element:"))
l.append(x)
t=tuple(l)
print(t)
d=int(input("enter element to delete:"))
l.remove(d)
t=tuple(l)
print(t)
ind=int(input("enter search index:"))
print(t[ind])
